# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: Julius Künzel <julius.kuenzel@kde.org>

INSTALL (FILES 

secondary_color_correction.xml
secondary_color_correction_v2.xml
shut_off.xml
native_transition_active.xml
native_transition_presets.xml

DESTINATION ${KDE_INSTALL_DATADIR}${DATA_INSTALL_PREFIX}/effect-templates)
