# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: Kdenlive contributors

install(FILES
    WN8DarkGreen.colors
    WN8DarkOrange.colors
    WN8DarkPurple.colors
    WN8DarkRed.colors
    WN8DarkTurquoise.colors
    WN8DarkYellow.colors
    WN8GrayGreen.colors
    WN8GrayOrange.colors
    WN8GrayPurple.colors
    WN8GrayRed.colors
    WN8GrayTurquoise.colors
    WN8GrayYellow.colors
    WN8LightGreen.colors
    WN8LightOrange.colors
    WN8LightPurple.colors
    WN8LightRed.colors
    WN8LightTurquoise.colors
    WN8LightYellow.colors
    DESTINATION ${KDE_INSTALL_DATADIR}/color-schemes)
