# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: Jean-Baptiste Mardelle <jb@kdenlive.org>, Julius Künzel <julius.kuenzel@kde.org>, Massimo Stella <maxstar@tin.it>

INSTALL (FILES 

audiobalance.xml
audiolevelgraph.xml
audiomap.xml
audiopan.xml
audiospectrum.xml
audiowave.xml
audiowaveform.xml
boxblur.xml
box_blur.xml
brightness.xml
burningtv.xml
channelcopy.xml
copychannelstostereo.xml
charcoal.xml
chroma_hold.xml
chroma.xml
crop.xml
dance.xml
dropshadow.xml
dust.xml
dynamic_loudness.xml
dynamictext.xml
fade_from_black.xml
fade_to_black.xml
fadein.xml
fadeout.xml
freeze.xml
gain.xml
gamma.xml
gpstext.xml
gpsgraphic.xml
gradientmap.xml
grain.xml
greyedge.xml
greyscale.xml
hsl_primaries.xml
hsl_range.xml
invert.xml
lift_gamma_gain.xml
lightshow.xml
loudness.xml
luma.xml
lumakey.xml
lumaliftgaingamma.xml
mask_start.xml
mask_start_frei0r_alphaspot.xml
mask_start_frei0r_select0r.xml
mask_start_rotoscoping.xml
mask_start_shape.xml
mask_apply.xml
mirror.xml
motion_transform_blur.xml
native_brightness_contrast.xml
native_motion_vector_blur.xml
native_spatial_blur.xml
native_blur_motion.xml
native_magnify_warp.xml
native_pinch_punch.xml
native_fisheye_warp.xml
native_axis_stretch.xml
native_corner_pin.xml
native_warp_chroma.xml
native_distort_chroma.xml
native_shake.xml
native_warp_waves.xml
native_warp_bubble2.xml
mono.xml
mute.xml
normalise.xml
obscure.xml
oldfilm.xml
pan_zoom.xml
pillar_echo.xml
qtblend.xml
qtcrop.xml
rboctaveshift.xml
rbpitchscale.xml
rotation_keyframable.xml
rotate-3-way.xml
rotation.xml
rotoscoping.xml
scratchlines.xml
shake.xml
pending_effects.xml
sepia.xml
shape.xml
shear.xml
speed.xml
spot_remover.xml
strobe.xml
swapchannels.xml
timer.xml
tcolor.xml
threshold.xml
tracker.xml
typewriter.xml
vidstab.xml
vignette.xml
volume.xml
wave.xml

DESTINATION ${KDE_INSTALL_DATADIR}${DATA_INSTALL_PREFIX}/effects)

add_subdirectory(update)
add_subdirectory(avfilter)
add_subdirectory(frei0r)
add_subdirectory(ladspa)
add_subdirectory(movit)
add_subdirectory(sox)
add_subdirectory(templates)
